
DROP TABLE Oceny_czastkowe CASCADE CONSTRAINTS;
DROP TABLE Zapisy CASCADE CONSTRAINTS;
DROP TABLE Student_Semestr CASCADE CONSTRAINTS;
DROP TABLE Semestry CASCADE CONSTRAINTS;
DROP TABLE Przedmioty CASCADE CONSTRAINTS;
DROP TABLE Studenci CASCADE CONSTRAINTS;
DROP TABLE Wykladowcy CASCADE CONSTRAINTS;
DROP TABLE Kierunki CASCADE CONSTRAINTS;


COMMIT;


SELECT table_name 
FROM user_tables 
WHERE table_name IN ('KIERUNKI', 'STUDENCI', 'WYKLADOWCY', 'PRZEDMIOTY', 'SEMESTRY', 'STUDENT_SEMESTR', 'ZAPISY', 'OCENY_CZASTKOWE');
SELECT 'All tables have been successfully dropped!' AS Status FROM dual;